server:
  port: 8080
  servlet:
    context-path: /meteo
management:
  endpoints:
    web:
      base-path: /meteo/management
  endpoint:
    flyway:
      enabled: true
  server:
    port: 8090
spring:
 profiles:
   active: dev
 jpa:
   show-sql: true
   open-in-view: true
   hibernate:
     ddl-auto: create-drop
   properties:
     javax.persistence.validation.mode: ddl
     hibernate.dialect.storage_engine: innodb
     hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
     hibernate.format_sql: false
     hibernate.cache.use_second_level_cache: false
     hibernate.cache.use_query_cache: false
     hibernate.generate_statistics: false
     hibernate.jdbc.batch_size: 500
 datasource:
   hikari:
     jdbc-url: jdbc:mysql://localhost:32768/meteo?autoReconnect=true&useSSL=false
     username: root
     password: 12345
     minimum-idle: 1
     maximum-pool-size: 20
     max-lifetime: 600000
     connection-timeout: 10000
 rabbitmq:
   port: 32787
   host: localhost
   username: admin
   password: admin
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.data.jpa.repository.JpaRepository: debug